name: 'Test js2cpp'
on:
  push:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      name: 'setup node'
      with:
        node-version: '14.x'

    - name: 'Installing deps'
      run: npm install

    - name: 'Compiling'
      run: ./compile.sh
      shell: bash
      
    - name: 'Running'
      run: g++ output/js_result.cpp -o output/js_bin && output/js_bin>log.txt
      shell: bash

    - name: 'Check results'
      run:  diff log.txt expected_results.txt && exit $?
      shell: bash
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
         name: output
         path: output
