name: 'Test js2cpp'
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      name: 'setup node'
      with:
        node-version: '14.x'
    - name: Set up MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x86
        
    - name: 'Installing deps'
      run: npm install

    - name: 'Preparing env'
      run: |
       echo "Creating folder output..."
       mkdir -p output/logs
       echo "Copy src to output/src"
       cp -r src/ output/src
      shell: bash

    - name: 'Compiling'
      run: python3 ./tests/build.py

    - name: 'Running'
      run: python3 ./tests/run.py
    
    - name: Upload artifact full
      uses: actions/upload-artifact@v3
      with:
         name: full
         path: output
         if-no-files-found: error
       
    - name: Upload artifact exe
      uses: actions/upload-artifact@v3
      with:
         name: exe
         path: output/*.exe
         if-no-files-found: error
       
    - name: Upload artifact elf
      uses: actions/upload-artifact@v3
      with:
         name: elf
         path: output/*.elf
         if-no-files-found: error
